---
- name: Job
  hosts: all
  become: yes
  vars_files:
          - /wsr-skillcloud/Users/privvars.yml
  tasks:
          - name: Apt Update
            apt: update_cache=yes force_apt_get=yes

          - name: Install curl
            apt:
                    name: "{{ item }}"
                    state: present
            with_items:
                    - curl
                    - fail2ban
                    - rsyslog

          - name: Enable UFW
            ufw:
                    state: enabled
                    policy: allow

          - name: Allow ports
            ufw:
                    rule: allow
                    port: "{{ item }}"
            with_items:
                    - 80
                    - 8888
                    - 1467
                    - 514

          - name: Change line PORT sshd in /etc/ssh/sshd_config
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: '#Port'
                    line: 'Port 1467'
                    backrefs: yes

          - name: Change line PublicKeyAuthentication sshd in /etc/ssh/sshd_config
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: '#PubkeyAuthentication'
                    line: 'PubkeyAuthentication yes'
                    backrefs: yes

          - name: Add USER "{{ skillcloud.users[0] }}"
            user:
                    name: "{{ skillcloud.users[0] }}"
                    state: present
                    password: "{{ skillcloud.passwords[0] | password_hash('sha512') }}"
                    shell: /bin/bash
                    createhome: yes

          - name: Add USER "{{ skillcloud.users[1] }}"
            user:
                    name: "{{ skillcloud.users[1] }}"
                    state: present
                    password: "{{ skillcloud.passwords[1] | password_hash('sha512') }}"
                    shell: /bin/bash
                    createhome: yes

          - name: Add USER "{{ skillcloud.users[2] }}"
            user:
                    name: "{{ skillcloud.users[2] }}"
                    state: present
                    password: "{{ skillcloud.passwords[2] | password_hash('sha512') }}"
                    shell: /bin/bash
                    createhome: yes


          - name: MKDIR .ssh "{{ skillcloud.users[0] }}"
            file:
                    path: "/home/{{ skillcloud.users[0] }}/.ssh"
                    state: directory
                    owner: "{{ skillcloud.users[0] }}"
                    group: "{{ skillcloud.users[0] }}"
                    mode: u+rwx

          - name: MKDIR .ssh "{{ skillcloud.users[1] }}"
            file:
                    path: "/home/{{ skillcloud.users[1] }}/.ssh"
                    state: directory
                    owner: "{{ skillcloud.users[1] }}"
                    group: "{{ skillcloud.users[1] }}"
                    mode: u+rwx

          - name: MKDIR .ssh "{{ skillcloud.users[2] }}"
            file:
                    path: "/home/{{ skillcloud.users[2] }}/.ssh"
                    state: directory
                    owner: "{{ skillcloud.users[2] }}"
                    group: "{{ skillcloud.users[2] }}"
                    mode: u+rwx

          - name: Add public key in authorized file user1
            lineinfile:
                    create: true
                    line: "{{ skillcloud.publickey }}"
                    dest: "/home/{{ skillcloud.users[0] }}/.ssh/authorized_keys"

          - name: Add public key in authorized file user2
            lineinfile:
                    create: true
                    line: "{{ skillcloud.publickey }}"
                    dest: "/home/{{ skillcloud.users[1] }}/.ssh/authorized_keys"

          - name: Add public key in authorized file user3
            lineinfile:
                    create: true
                    line: "{{ skillcloud.publickey }}"
                    dest: "/home/{{ skillcloud.users[2] }}/.ssh/authorized_keys"

          - name: mv jail.conf to jail.local
            command: "cp /etc/fail2ban/jail.{conf,local}"

          - name: Change file /etc/fail2ban/jail.local line one
            lineinfile:
                    dest: /etc/fail2ban/jail.local
                    regexp: ''
                    line: "[ssh]"

          - name: Change file /etc/fail2ban/jail.local line two
            lineinfile:
                    dest: /etc/fail2ban/jail.local
                    regexp: ''
                    line: "findtime = 3600"

          - name: Change file /etc/fail2ban/jail.local line three
            lineinfile:
                    dest: /etc/fail2ban/jail.local
                    regexp: ''
                    line: "maxretry = 6"

          - name: Change file /etc/fail2ban/jail.local line four
            lineinfile:
                    dest: /etc/fail2ban/jail.local
                    regexp: ''
                    line: "bantime = 86400"

          - name: Restart fail2ban
            systemd:
                    name: fail2ban
                    state: restarted

          - name: Add clean journald 30d, crontab
            cron:
                    name: "a job for weekly"
                    special_time: weekly
                    job: "journalctl --vacuum-time=30d"

          - name: Set timezone to Europe/Moscow
            timezone:
                    name: Europe/Moscow

          - name: Copy script to install Docker-ce and Zabbix agent
            copy:
                    src: install-docker-zabbix-agent.sh
                    dest: /bin
                    mode: a+x 

          - name: Run script to install Docker-ce and Zabbix agent
            command: '/bin/bash install-docker-zabbix-agent.sh'

          - name: Copy script to install docker-compose
            copy:
                    src: /wsr-skillcloud/docker-compose.sh
                    dest: /bin
                    mode: a+x

          - name: Change file /etc/rsyslog.conf allow port UDP line one
            lineinfile:
                    path: /etc/rsyslog.conf
                    regexp: '#module(load="imudp")'
                    line: 'module(load="imudp")'
                    backrefs: yes

          - name: Change file /etc/rsyslog.conf allow port UDP line two
            lineinfile:
                    path: /etc/rsyslog.conf
                    regexp: '#input(type="imudp" port="514")'
                    line: 'input(type="imudp" port="514")'
                    backrefs: yes

          - name: Change file /etc/rsyslog.conf allow port TCP line one
            lineinfile:
                    path: /etc/rsyslog.conf
                    regexp: '#module(load="imtcp")'
                    line: 'module(load="imtcp")'
                    backrefs: yes

          - name: Change file /etc/rsyslog.conf allow port TCP line two
            lineinfile:
                    path: /etc/rsyslog.conf
                    regexp: '#input(type="imtcp" port="514")'
                    line: 'input(type="imtcp" port="514")'
                    backrefs: yes

          - name: Run cript to install docker-compose
            command: '/bin/bash docker-compose.sh'

          - name: MKDIR skillcloud-ngsite
            file:
                    path: /skillcloud-ngsite
                    state: directory

          - name: Copy file to destination host in directory /skillcloud-ngsite
            copy:
                    src: "{{ item }}" 
                    dest: /skillcloud-ngsite
            with_items:
                    - /wsr-skillcloud/docker-compose.yml
                    - /wsr-skillcloud/Dockerfile-site
                    - /wsr-skillcloud/Dockerfile-balance
                    - /wsr-skillcloud/index.html
                    - /wsr-skillcloud/balance.conf

          - name: Restart sshd
            systemd:
                    name: sshd
                    state: restarted

          - name: Reload UFW
            ufw:
                    state: reloaded
                    policy: allow

          - name: Reboot VM
            reboot:
