---
# tasks file for rsyslog
- name: Copy script to changefile.sh
  copy:
          src: changefile.sh
          dest: /bin
          mode: a+x

- name: Run script
  command: '/bin/bash changefile.sh'
  notify:
          - restart rsyslog
