---
# tasks file for ufw
- name: Enable UFW
  ufw:
          state: enabled
          policy: allow

- name: Allow ports
  ufw:
          rule: allow
          port: "{{ item }}"
  with_items:
          - 80
          - 8888
          - 1467
          - 514
  notify:
          - reload ufw
